Code for given data interpretation - Understanding the given data, its format and structure.


In [1]:
!pip install rasterio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.2/22.2 MB 43.3 MB/s eta 0:00:00


In [4]:
#Import libraries
import rasterio                    #For handelling raster (here .tif files)
import numpy as np                 #For numerical operations on arrays
import matplotlib.pyplot as plt    #For plotting and visualizing image data

In [6]:
files = ["/content/drive/MyDrive/iitisoc_ps1 (1)/sar_dataset/Train_Val_Oil_Spill_images/Oil/00000.tif",
       "/content/drive/MyDrive/iitisoc_ps1 (1)/sar_dataset/Train_Val_Oil_Spill_images/Oil/00001.tif",
       "/content/drive/MyDrive/iitisoc_ps1 (1)/sar_dataset/Train_Val_Oil_Spill_images/Oil/00002.tif"]  #Path to first 3 .tif files for their data interpretation
for file in files:
  with rasterio.open(file) as src:
    print("Metadata:", src.meta)              # Print metadata such as dimensions, driver, dtype, etc.
    print("Number of bands:", src.count)      # Print number of bands
    data = src.read()                         # Read all bands into a 3D NumPy array (shape- bands × rows × columns)
    print("Data shape:", data.shape)
    print("Data type:", data.dtype)
    img = src.read(1)                         # Read just the first band
    print("Original Array", img)              # Print pixel values as a 2D array

Metadata: {'driver': 'GTiff', 'dtype': 'float32', 'nodata': None, 'width': 2048, 'height': 2048, 'count': 2, 'crs': CRS.from_wkt('GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]'), 'transform': Affine(8.983152841195215e-05, 0.0, 3.9656639450910203,
       0.0, -8.983152841195215e-05, 55.33396508271642)}
Number of bands: 2
Data shape: (2, 2048, 2048)
Data type: float32
Original Array [[-32.444515 -32.54523  -32.182518 ... -35.516655 -38.529987 -37.48489 ]
 [-30.644533 -31.674006 -33.209736 ... -34.780228 -37.760834 -37.98035 ]
 [-28.903502 -30.722063 -34.657368 ... -35.04511  -35.831825 -37.47058 ]
 ...
 [-32.219948 -32.634033 -32.42556  ... -38.747795 -38.819576 -38.713764]
 [-30.12145  -29.374    -28.869383 ... -39.80025  -40.62422  -

Metadata: {'driver': 'GTiff', 'dtype': 'float32', 'nodata': None, 'width': 2048, 'height': 2048, 'count': 2, 'crs': CRS.from_wkt('GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]'), 'transform': Affine(8.983152841195215e-05, 0.0, 5.079664728927639,
       0.0, -8.983152841195215e-05, 55.56501177379196)}
Number of bands: 2
Data shape: (2, 2048, 2048)
Data type: float32
Original Array [[-29.659838 -29.486334 -30.127487 ... -37.233242 -37.49049  -38.202274]
 [-30.29175  -29.73069  -30.764286 ... -34.96422  -35.22926  -35.446842]
 [-33.16665  -31.529123 -32.135914 ... -34.894474 -36.092278 -37.395584]
 ...
 [-32.364075 -31.988588 -32.392815 ... -29.275852 -28.904882 -29.70323 ]
 [-33.132942 -33.432632 -34.149952 ... -30.889492 -30.898525 -3

Metadata: {'driver': 'GTiff', 'dtype': 'float32', 'nodata': None, 'width': 2048, 'height': 2048, 'count': 2, 'crs': CRS.from_wkt('GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]'), 'transform': Affine(8.983152841195215e-05, 0.0, 5.90018590944241,
       0.0, -8.983152841195215e-05, 55.5435420385015)}
Number of bands: 2
Data shape: (2, 2048, 2048)
Data type: float32
Original Array [[-39.228138 -39.08132  -38.630756 ... -31.025257 -30.837393 -30.848083]
 [-38.371883 -39.11332  -39.3082   ... -30.211792 -30.24992  -30.912737]
 [-36.99314  -37.733124 -38.64546  ... -31.19314  -31.5186   -32.02333 ]
 ...
 [-39.603485 -39.548893 -38.963516 ... -38.58452  -38.78878  -37.04382 ]
 [-40.23586  -41.212383 -40.833694 ... -36.784035 -36.695484 -36.